version: '2'
services:
  build:
    build: build
    volumes:
      - /tmp/repos:/tmp/repos
      - /tmp/webapps:/tmp/build

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - /tmp/webapps:/usr/local/tomcat/webapps
