version: '2'
services:
  build:
    build: build
    volumes:
      - /tmp/repos:/tmp/repos
      - webapps:/tmp/build

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - webapps:/usr/local/tomcat/webapps

volumes:
  webapps: